// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcljlwlDblQYznFqo6F6Ub8RqWV3huLCw',
    appId: '1:318728633467:web:9e8f6adef8d3034d2236de',
    messagingSenderId: '318728633467',
    projectId: 'nscproject-319ed',
    authDomain: 'nscproject-319ed.firebaseapp.com',
    storageBucket: 'nscproject-319ed.firebasestorage.app',
    measurementId: 'G-JJQ1R2M22V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARgTsXPWBqlBYeJskAngTPs0Ee0AzVmOs',
    appId: '1:318728633467:android:8302a6a6dff26aef2236de',
    messagingSenderId: '318728633467',
    projectId: 'nscproject-319ed',
    storageBucket: 'nscproject-319ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQbWzRt5ifF_XRxcAvXc8Fmqyrgps8BfE',
    appId: '1:318728633467:ios:0d312110751bc4932236de',
    messagingSenderId: '318728633467',
    projectId: 'nscproject-319ed',
    storageBucket: 'nscproject-319ed.firebasestorage.app',
    iosBundleId: 'com.example.nsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQbWzRt5ifF_XRxcAvXc8Fmqyrgps8BfE',
    appId: '1:318728633467:ios:0d312110751bc4932236de',
    messagingSenderId: '318728633467',
    projectId: 'nscproject-319ed',
    storageBucket: 'nscproject-319ed.firebasestorage.app',
    iosBundleId: 'com.example.nsc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcljlwlDblQYznFqo6F6Ub8RqWV3huLCw',
    appId: '1:318728633467:web:d8aad4915e0af58b2236de',
    messagingSenderId: '318728633467',
    projectId: 'nscproject-319ed',
    authDomain: 'nscproject-319ed.firebaseapp.com',
    storageBucket: 'nscproject-319ed.firebasestorage.app',
    measurementId: 'G-5Y1GYWYW1P',
  );
}
